# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='aiospbstu',
    version='1.0.0',
    description='Asynchronous API wrapper for PolyTech Schedule API',
    author='MrMrRobat',
    author_email='appkiller16@gmail.com',
    packages=['aiospbstu', 'aiospbstu.types', 'aiospbstu.utils'],
    package_data={},
    install_requires=[
        'aiohttp==3.5.4', 'async-timeout==3.0.1', 'attrs==19.1.0',
        'certifi==2019.3.9', 'chardet==3.0.4', 'idna==2.8', 'multidict==4.5.2',
        'pydantic==0.30', 'yarl==1.3.0'
    ],
)
